### ISSUE TITLE
tendis 部署到k8s中运行失败

### ISSUE THREAD

**Issue by linydquantil** [Tencent/Tendis#143]
k8s version:  1.17

这是yaml file:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tendis
  labels:
    app: tendis
spec:
  replicas: 1
  minReadySeconds: 3
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: tendis
  template:
    metadata:
      labels:
        app: tendis
    spec:
      containers:
        - name: tendis
          image: tencentdbforkv/tendisplus:v2.3.5
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - containerPort: 51002
              name: app-port
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "128m"
              memory: 128Mi
```
执行kubectl logs 获取日志如下：

```
port 51002
bind 10.1.0.145 
loglevel debug
logdir /data1/tendis/51002/log
dumpdir /data1/tendis/51002/dump
dir /data1/tendis/51002/db
pidfile /data1/tendis/51002/tendisplus.pid
slowlog /data1/tendis/51002/log/slowlog
rocks.blockcachemb 4096
storage rocks
generallog 0
checkkeytypeforsetcmd off
cluster-enabled no
requirepass test
masterauth test
+ ../bin/tendisplus /data1/tendis/51002/tendisplus.conf
start.sh: line 28:    26 Illegal instruction     (core dumped) ../bin/tendisplus ${dir}/${port}/tendisplus.conf
```
另外就是能否提供dockerfile 官方镜像更新的比较慢哦
